Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/debian12"
  config.vm.hostname = "proyectoIA"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "public_network"
  config.vm.synced_folder "../codi", "/home/vagrant/Bot"
  config.vm.synced_folder "../web", "/var/www/html"
  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
  # Display the VirtualBox GUI when booting the machine.
    vb.gui = false
  # Customize the amount of memory on the VM:
    vb.name = "proyectoIA"
    vb.memory = "4096"
    vb.cpus = "2"
  end

# PROVISIONS
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    # COMO INSTALAR Node.js
    curl -sL https://deb.nodesource.com/setup_18.x | bash -
    apt-get install -y nodejs
    cd /home/vagrant/Bot/
    sudo npm install -g npm@10.9.0
    npm fund
    npm install -g discord.js
    npm fund
  SHELL
end
